//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3705.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.0.3705.0.
// 
using System.Diagnostics;
using System.Xml.Serialization;
using System;
using System.Web.Services.Protocols;
using System.ComponentModel;
using System.Web.Services;


/// <remarks/>
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="DataWebServiceSoap", Namespace="http://localhost/webservices/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Firework))]
public class DataWebService : System.Web.Services.Protocols.SoapHttpClientProtocol 
{
    
    /// <remarks/>
    public DataWebService() 
    {
        this.Url = "http://localhost/demo/DataWebService.asmx";
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/webservices/RocketHome", RequestNamespace="http://localhost/webservices/", ResponseNamespace="http://localhost/webservices/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Rocket RocketHome(string name) 
    {
        object[] results = this.Invoke("RocketHome", new object[] {
                                                                      name});
        return ((Rocket)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginRocketHome(string name, System.AsyncCallback callback, object asyncState) 
    {
        return this.BeginInvoke("RocketHome", new object[] {
                                                               name}, callback, asyncState);
    }
    
    /// <remarks/>
    public Rocket EndRocketHome(System.IAsyncResult asyncResult) 
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((Rocket)(results[0]));
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/webservices/")]
public class Rocket : Firework 
{
    
    /// <remarks/>
    public System.Double Apogee;
    
    /// <remarks/>
    public System.Double Thrust;
}

/// <remarks/>
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/webservices/")]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(Rocket))]
public class Firework 
{
    
    /// <remarks/>
    public string Name;
    
    /// <remarks/>
    public System.Double Mass;
    
    /// <remarks/>
    public System.Decimal Price;
}
